Pass `CPPFLAGS` separately to `libuv`'s configure script
Do not combine `CPPFLAGS` into `CFLAGS` because `CFLAGS` is passed to
the linker when buiding `libuv`. If `CPPFLAGS` contains `-Xclang
-fopenmp`, it will confuse the linker and produces error `clang:
error: unsupported option '-fopenmp'`. See:
https://github.com/libuv/libuv/discussions/3966

Closes #345.